library(ctsmTMB)
library(nanoparquet)

model <- ctsmTMB$new()

# TODO : Add the outdoor temperature as an input 
# TODO : Check the dimensionality and units, log scale etc. 

# State 
# [TT, Tc] 
# TT = alpha Tt + (1 - alpha) Tb
# Tc = Tb

# Linear SDE 
model$addSystem(
    dTT ~  1/exp(log_Ctank) * (exp(log_COP)*Pel - Qdist)*dt     + exp(log_sigma_TT)*dw,
    dTc ~ (1/exp(log_tau) * (Tr - Tc) + exp(log_lambda)*Pel)*dt + exp(log_sigma_Tc)*dw
)

model$addObs(
   Tt ~ (1 / exp(log_alpha)*TT + (1 - 1/exp(log_alpha))*Tc),
   Tb ~ Tc 
)

model$setVariance(
    Tt ~ sigma_Tt,
    Tb ~ sigma_Tb
)

model$addInput(
    Pel, 
    Qdist, 
    Tr
)

model$setParameter( 
    log_Ctank    = c(initial=log(10460000.0), lower=log(8000000.0), upper=log(12500000.0)), # Tank total capacity
    log_COP      = c(initial=log(4.5) , lower=log(3.0) , upper=log(6.0)),          # Coefficient of Performence 
    log_tau      = c(initial=log(3600), lower=log(1000), upper=log(10800)),        # Tank bottom temperature flush time constant
    log_lambda   = c(initial=log(1e-6), lower=log(1e-8), upper=log(1e-4)),         # Charging mixing gain 
    log_alpha    = c(initial=log(0.5) , lower=-Inf     , upper=0.0),               # Mixing ratio proxy
    # Process noise  
    log_sigma_TT = c(initial=log(0.05), lower=-Inf, upper=log(0.15)),              # Process noise state 1
    log_sigma_Tc = c(initial=log(0.05), lower=-Inf, upper=log(0.15)),              # Process noise state 2
    # Measurement noise
    sigma_Tt = c(initial=0.1, lower=0.01, upper=0.2),                              # Process noise measurement 1
    sigma_Tb = c(initial=0.1, lower=0.01, upper=0.2)                               # Process noise measurement 2
)

# model$setParameter( 
#     log_Ctank    = c(initial=log(10460000.0), lower=log(10460.0), upper=log(10460.0)), # Tank total capacity
#     log_COP      = c(initial=log(4.5) , lower=log(4.5) , upper=log(4.5)),          # Coefficient of Performence 
#     log_tau      = c(initial=log(3600), lower=log(1000), upper=log(10800)),        # Tank bottom temperature flush time constant
#     log_lambda   = c(initial=log(1e-7), lower=log(1e-7), upper=log(1e-6)),         # Charging mixing gain 
#     log_alpha    = c(initial=log(0.5) , lower=log(0.5) , upper=log(0.5)),               # Mixing ratio proxy
#     # Process noise  
#     log_sigma_TT = c(initial=log(0.05), lower=-Inf, upper=log(0.1)),              # Process noise state 1
#     log_sigma_Tc = c(initial=log(0.05), lower=-Inf, upper=log(0.1)),              # Process noise state 2
#     # Measurement noise
#     sigma_Tt = c(initial=0.1, lower=0.01, upper=0.2),                              # Process noise measurement 1
#     sigma_Tb = c(initial=0.1, lower=0.01, upper=0.2)                               # Process noise measurement 2
# )

# %% Read the data from the parquet file
raw    <- read_parquet("data/karno-410708_raw_k0001.parquet")
t0     <- as.POSIXct("2026-05-13", tz="UTC")
t1     <- as.POSIXct("2026-05-25", tz="UTC")
grid   <- seq(t0, t1 - 300, by=300)
window <- match(grid, raw$UTC_DateTime)   # NA where a 5-min sample is missing

# %% Help function 
# fill isolated NA gaps (missing samples, sensor dropouts) by linear
fill_na <- function(x) {
    idx <- seq_along(x)
    ok  <- !is.na(x)
    approx(idx[ok], x[ok], xout=idx, rule=2)$y
}

fill_obs <- function(x, limit=gap.limit) {
    idx    <- seq_along(x)
    ok     <- !is.na(x)
    filled <- approx(idx[ok], x[ok], xout=idx, rule=2)$y
    run    <- rle(is.na(x))
    long.na <- rep(run$values & run$lengths > limit, run$lengths)
    filled[long.na] <- NA
    filled
}

# %% Data cleaning 
gap.limit = 4L

Pel   <- fill_na(raw$`P_el,HP,air`[window])     # W
Qdist <- fill_na(raw$`Q̇_dist`[window]) * 1000   # kW -> W
Tr    <- fill_na(raw$`T_dist,ret`[window])      # degC


# Filter for absence of HP signal
z.air  <- raw$`z_HP,air`[window]
z.geo  <- raw$`z_HP,geo`[window]
hp.off <- !z.air & !z.geo
hp.off[is.na(hp.off)] <- FALSE   # unknown HP state -> not confirmed quiet, excluded below

# Prepare the output
t.seq <- as.numeric(difftime(grid, grid[1], units="secs"))
df.obs <- data.frame(
    t      = t.seq,
    Pel    = Pel,
    Qdist  = Qdist,
    Tr     = Tr,
    Tt     = NA,   # placeholder: filled in by simulate() below (states generated by the model)
    Tb     = NA
)


# --- Fit model to the real measured Ttop / Tbot --------------------------
Ttop.meas <- fill_obs(raw$T_top[window])   # degC, NA over gaps > gap.limit
Tbot.meas <- fill_obs(raw$T_bot[window])   # degC, NA over gaps > gap.limit


# Manually excise an unreliable stretch of the log (e.g. a known sensor
# fault / maintenance window). Marking it NA -- rather than dropping rows --
# keeps the time grid regular while forcing an extra split in the fitted
# portions, exactly like a long dropout would.
excl.start <- as.POSIXct("2026-05-20 07:00:00", tz="UTC")
excl.end   <- as.POSIXct("2026-05-20 11:00:00", tz="UTC")
excl       <- grid >= excl.start & grid < excl.end
Ttop.meas[excl] <- NA
Tbot.meas[excl] <- NA

df.fit <- df.obs
df.fit$Tt <- Ttop.meas
df.fit$Tb <- Tbot.meas

valid <- !is.na(Ttop.meas) & !is.na(Tbot.meas) & hp.off
run   <- rle(valid)
run.end   <- cumsum(run$lengths)
run.start <- run.end - run$lengths + 1
segments  <- data.frame(start=run.start, end=run.end)[run$values, ]

min.seg.len <- 4L
segments <- segments[(segments$end - segments$start + 1) >= min.seg.len, ]

cat(sprintf("Fitting across %d data portion(s):\n", nrow(segments)))
for (i in seq_len(nrow(segments))) {
    cat(sprintf("  [%d] %s -> %s\n", i,
                format(grid[segments$start[i]]), format(grid[segments$end[i]])))
}

n.seg <- nrow(segments)

seg.data <- vector("list", n.seg)
seg.x0   <- vector("list", n.seg)
seg.p0   <- vector("list", n.seg)


for (i in seq_len(n.seg)) {
    idx <- segments$start[i]:segments$end[i]
    seg.data[[i]] <- data.frame(
        t         = t.seq[idx] - t.seq[idx[1]],
        Pel       = Pel[idx],
        Qdist     = Qdist[idx],
        Tr        = Tr[idx],
        Tt        = Ttop.meas[idx],
        Tb        = Tbot.meas[idx]
    )
    # Initial condition = the actual measurement at this segment's first
    # (by construction, non-NA) sample -- not the state propagated/guessed
    # forward from the end of the previous segment.
    seg.x0[[i]] <- c(Ttop.meas[idx[1]], Tbot.meas[idx[1]])
    seg.p0[[i]] <- 0.1 * diag(2)
}

seg.nll <- lapply(seq_len(n.seg), function(i) {
    model$likelihood(
        data          = seg.data[[i]],
        method        = "lkf",
        initial.state = list(x0 = seg.x0[[i]], p0 = seg.p0[[i]]),
        silent        = TRUE
    )
})

joint.nll <- function(p) Reduce(`+`, lapply(seg.nll, function(h) h$fn(p)))
joint.gr  <- function(p) Reduce(`+`, lapply(seg.nll, function(h) h$gr(p)))
joint.he  <- function(p) Reduce(`+`, lapply(seg.nll, function(h) h$he(p)))

free.init  <- model$getParameters(type = "free", value = "initial")
free.lower <- model$getParameters(type = "free", value = "lower")
free.upper <- model$getParameters(type = "free", value = "upper")

# This is a black box nonlinear solver. Check the documentation 
opt <- nlminb(
    start     = free.init,
    objective = joint.nll,
    gradient  = joint.gr,
    hessian   = joint.he,
    lower     = free.lower,
    upper     = free.upper,
    control   = list(trace = 1, iter.max = 1e4, eval.max = 1e4)
)

names(opt$par) <- names(free.init)

cat(opt$message, "\n")
print(rbind(par = opt$par, lower = free.lower, upper = free.upper))

cat(sprintf("\nJoint multi-segment fit: %s\n", opt$message))
cat(sprintf("Negative log-likelihood at optimum: %.4f (summed over %d segments)\n",
            opt$objective, n.seg))

            
fixed.idx <- which(free.lower == free.upper)
free.idx  <- setdiff(seq_along(opt$par), fixed.idx)
se <- rep(NA_real_, length(opt$par))
se[free.idx] <- sqrt(diag(solve(joint.he(opt$par)[free.idx, free.idx])))
zval <- opt$par / se
pval <- 2 * pnorm(-abs(zval))
print(data.frame(estimate = opt$par, std.error = se, z.value = zval, p.value = pval))

# Map the log_* rows back to physical units: theta = exp(phi). By the delta
# method Var(theta) ~= (dtheta/dphi)^2 * Var(phi) = theta^2 * Var(phi), so
# SE(theta) ~= theta_hat * SE(phi) -- exact to first order since
# dtheta/dphi = theta for a pure exp() map. z/p are omitted here: the Wald
# test above is against phi=0 (i.e. theta=1), which isn't a physically
# meaningful null for a positive quantity like a capacity or a noise sigma.
is.log.par <- grepl("^log_", names(opt$par))
phys.estimate  <- ifelse(is.log.par, exp(opt$par), opt$par)
phys.std.error <- ifelse(is.log.par, phys.estimate * se, se)
names(phys.estimate) <- sub("^log_", "", names(opt$par))
cat("\nBack-transformed (physical-unit) parameter estimates:\n")
print(data.frame(estimate = phys.estimate, std.error = phys.std.error,
                  row.names = names(phys.estimate)))


fitted.pars <- model$getParameters(value = "initial")
fitted.pars[names(opt$par)] <- opt$par

# --- Open-loop simulation with the fitted parameters, per segment --------
seg.sim <- lapply(seq_len(n.seg), function(i) {
    model$simulate(
        data                = seg.data[[i]],
        pars                = fitted.pars,
        method              = "lkf",
        simulation.timestep = 300.0,
        n.sims              = 1,
        cpp.seeds           = c(20, 20),
        initial.state       = list(x0 = seg.x0[[i]], p0 = seg.p0[[i]])
    )
})

# Full-grid vectors, NA outside the fitted segments (those stretches were
# never simulated -- there is no meaningful open-loop trajectory to show
# across a manually-excised or too-long dropout).
Ttop.sim <- rep(NA_real_, length(grid))
Tbot.sim <- rep(NA_real_, length(grid))
for (i in seq_len(n.seg)) {
    idx <- segments$start[i]:segments$end[i]
    Ttop.sim[idx] <- seg.sim[[i]]$observations$Tt$i0
    Tbot.sim[idx] <- seg.sim[[i]]$observations$Tb$i0
}

# One page per calendar day.
t.hours <- df.obs$t / 3600
day.len <- 24
n.days  <- ceiling(max(t.hours) / day.len)

pdf("figures/enthalpy_fit_vs_measured.pdf", width=8, height=6)
for (d in seq_len(n.days) - 1) {
    day.idx <- which(t.hours >= d * day.len & t.hours < (d + 1) * day.len)
    if (length(day.idx) == 0) next

    par(mfrow=c(2,1), mar=c(2,4,2,1), oma=c(3,0,2,0))

    # --- Top panel: Tt ---
    ylim1 <- range(c(df.fit$Tt[day.idx], Ttop.sim[day.idx]), na.rm=TRUE)

    plot(t.hours[day.idx], df.fit$Tt[day.idx], type="l", col="gray50", lwd=1.5,
         xlab="", ylab="Tt [C]",
         main=sprintf("Simulated vs. measured Tt -- day %d", d + 1),
         ylim=ylim1)
    lines(t.hours[day.idx], Ttop.sim[day.idx], col="darkorange", lwd=1.5, lty=1)
    legend("topright", legend=c("measured", "simulated (fitted, open-loop)"),
           col=c("gray50", "darkorange"), lty=c(1,1), lwd=1.5, bty="n", cex=0.8)

    # --- Bottom panel: Tb ---
    ylim2 <- range(c(df.fit$Tb[day.idx], Tbot.sim[day.idx]), na.rm=TRUE)

    plot(t.hours[day.idx], df.fit$Tb[day.idx], type="l", col="gray50", lwd=1.5,
         xlab="", ylab="Tb [C]", main="Simulated vs. measured Tb",
         ylim=ylim2)
    lines(t.hours[day.idx], Tbot.sim[day.idx], col="darkorange", lwd=1.5, lty=1)
    legend("topright", legend=c("measured", "simulated (fitted, open-loop)"),
           col=c("gray50", "darkorange"), lty=c(1,1), lwd=1.5, bty="n", cex=0.8)

    mtext("Time [h]", side=1, outer=TRUE, line=1)
    par(mfrow=c(1,1))
}
dev.off()
